[project]
name = "openelections-data-or"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "natural-pdf>=0.7.0",
    "paddleocr>=3.7.0",
    "paddlepaddle>=3.3.1",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "pypdf>=6.16.2",
]
