name: Data Tests

on: [push, pull_request]

jobs:
  duplicate_entries:
    name: Duplicate entries
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Check out data
      uses: actions/checkout@v2.3.4
      with:
        path: data

    - name: Check out data tests
      uses: actions/checkout@v2.3.4
      with:
        repository: openelections/openelections-data-tests
        ref: v0.1.1
        path: data_tests

    - name: Run data tests
      run: python3 ${{ github.workspace }}/data_tests/run_tests.py duplicate_entries ${{ github.workspace }}/data
